// Adapted from:
//  https://github.com/samayo/country-json
List<Map> countries = [
  { 'country': 'Afghanistan', 'capital': 'Kabul' },
  { 'country': 'Albania', 'capital': 'Tirana' },
  { 'country': 'Algeria', 'capital': 'Alger' },
  { 'country': 'American Samoa', 'capital': 'Fagatogo' },
  { 'country': 'Andorra', 'capital': 'Andorra la Vella' },
  { 'country': 'Angola', 'capital': 'Luanda' },
  { 'country': 'Anguilla', 'capital': 'The Valley' },
  { 'country': 'Antarctica', 'capital': null },
  { 'country': 'Antigua and Barbuda', 'capital': 'Saint John\'s' },
  { 'country': 'Argentina', 'capital': 'Buenos Aires' },
  { 'country': 'Armenia', 'capital': 'Yerevan' },
  { 'country': 'Aruba', 'capital': 'Oranjestad' },
  { 'country': 'Australia', 'capital': 'Canberra' },
  { 'country': 'Austria', 'capital': 'Wien' },
  { 'country': 'Azerbaijan', 'capital': 'Baku' },
  { 'country': 'Bahamas', 'capital': 'Nassau' },
  { 'country': 'Bahrain', 'capital': 'al-Manama' },
  { 'country': 'Bangladesh', 'capital': 'Dhaka' },
  { 'country': 'Barbados', 'capital': 'Bridgetown' },
  { 'country': 'Belarus', 'capital': 'Minsk' },
  { 'country': 'Belgium', 'capital': 'Bruxelles [Brussel]' },
  { 'country': 'Belize', 'capital': 'Belmopan' },
  { 'country': 'Benin', 'capital': 'Porto-Novo' },
  { 'country': 'Bermuda', 'capital': 'Hamilton' },
  { 'country': 'Bhutan', 'capital': 'Thimphu' },
  { 'country': 'Bolivia', 'capital': 'La Paz' },
  { 'country': 'Bosnia and Herzegovina', 'capital': 'Sarajevo' },
  { 'country': 'Botswana', 'capital': 'Gaborone' },
  { 'country': 'Bouvet Island', 'capital': null },
  { 'country': 'Brazil', 'capital': 'Brasília' },
  { 'country': 'British Indian Ocean Territory', 'capital': null },
  { 'country': 'Brunei', 'capital': 'Bandar Seri Begawan' },
  { 'country': 'Bulgaria', 'capital': 'Sofia' },
  { 'country': 'Burkina Faso', 'capital': 'Ouagadougou' },
  { 'country': 'Burundi', 'capital': 'Bujumbura' },
  { 'country': 'Cambodia', 'capital': 'Phnom Penh' },
  { 'country': 'Cameroon', 'capital': 'Yaound' },
  { 'country': 'Canada', 'capital': 'Ottawa' },
  { 'country': 'Cape Verde', 'capital': 'Praia' },
  { 'country': 'Cayman Islands', 'capital': 'George Town' },
  { 'country': 'Central African Republic', 'capital': 'Bangui' },
  { 'country': 'Chad', 'capital': 'N\'Djam' },
  { 'country': 'Chile', 'capital': 'Santiago de Chile' },
  { 'country': 'China', 'capital': 'Peking' },
  { 'country': 'Christmas Island', 'capital': 'Flying Fish Cove' },
  { 'country': 'Cocos (Keeling) Islands', 'capital': 'West Island' },
  { 'country': 'Colombia', 'capital': 'Santaf' },
  { 'country': 'Comoros', 'capital': 'Moroni' },
  { 'country': 'Congo', 'capital': 'Brazzaville' },
  { 'country': 'Cook Islands', 'capital': 'Avarua' },
  { 'country': 'Costa Rica', 'capital': 'San Jos' },
  { 'country': 'Croatia', 'capital': 'Zagreb' },
  { 'country': 'Cuba', 'capital': 'La Habana' },
  { 'country': 'Cyprus', 'capital': 'Nicosia' },
  { 'country': 'Czech Republic', 'capital': 'Praha' },
  { 'country': 'Denmark', 'capital': 'Copenhagen' },
  { 'country': 'Djibouti', 'capital': 'Djibouti' },
  { 'country': 'Dominica', 'capital': 'Roseau' },
  { 'country': 'Dominican Republic', 'capital': 'Santo Domingo de Guzm' },
  { 'country': 'East Timor', 'capital': 'Dili' },
  { 'country': 'Ecuador', 'capital': 'Quito' },
  { 'country': 'Egypt', 'capital': 'Cairo' },
  { 'country': 'El Salvador', 'capital': 'San Salvador' },
  { 'country': 'England', 'capital': 'London' },
  { 'country': 'Equatorial Guinea', 'capital': 'Malabo' },
  { 'country': 'Eritrea', 'capital': 'Asmara' },
  { 'country': 'Estonia', 'capital': 'Tallinn' },
  { 'country': 'Ethiopia', 'capital': 'Addis Abeba' },
  { 'country': 'Falkland Islands', 'capital': 'Stanley' },
  { 'country': 'Faroe Islands', 'capital': 'Tórshavn' },
  { 'country': 'Fiji Islands', 'capital': 'Suva' },
  { 'country': 'Finland', 'capital': 'Helsinki [Helsingfors]' },
  { 'country': 'France', 'capital': 'Paris' },
  { 'country': 'French Guiana', 'capital': 'Cayenne' },
  { 'country': 'French Polynesia', 'capital': 'Papeete' },
  { 'country': 'French Southern territories', 'capital': null },
  { 'country': 'Gabon', 'capital': 'Libreville' },
  { 'country': 'Gambia', 'capital': 'Banjul' },
  { 'country': 'Georgia', 'capital': 'Tbilisi' },
  { 'country': 'Germany', 'capital': 'Berlin' },
  { 'country': 'Ghana', 'capital': 'Accra' },
  { 'country': 'Gibraltar', 'capital': 'Gibraltar' },
  { 'country': 'Greece', 'capital': 'Athenai' },
  { 'country': 'Greenland', 'capital': 'Nuuk' },
  { 'country': 'Grenada', 'capital': 'Saint George\'s' },
  { 'country': 'Guadeloupe', 'capital': 'Basse-Terre' },
  { 'country': 'Guam', 'capital': 'Aga' },
  { 'country': 'Guatemala', 'capital': 'Ciudad de Guatemala' },
  { 'country': 'Guinea', 'capital': 'Conakry' },
  { 'country': 'Guinea-Bissau', 'capital': 'Bissau' },
  { 'country': 'Guyana', 'capital': 'Georgetown' },
  { 'country': 'Haiti', 'capital': 'Port-au-Prince' },
  { 'country': 'Heard Island and McDonald Islands', 'capital': null },
  { 'country': 'Holy See (Vatican City State)', 'capital': 'Citt' },
  { 'country': 'Honduras', 'capital': 'Tegucigalpa' },
  { 'country': 'Hong Kong', 'capital': 'Victoria' },
  { 'country': 'Hungary', 'capital': 'Budapest' },
  { 'country': 'Iceland', 'capital': 'Reykjav' },
  { 'country': 'India', 'capital': 'New Delhi' },
  { 'country': 'Indonesia', 'capital': 'Jakarta' },
  { 'country': 'Iran', 'capital': 'Tehran' },
  { 'country': 'Iraq', 'capital': 'Baghdad' },
  { 'country': 'Ireland', 'capital': 'Dublin' },
  { 'country': 'Israel', 'capital': 'Jerusalem' },
  { 'country': 'Italy', 'capital': 'Roma' },
  { 'country': 'Ivory Coast', 'capital': 'Yamoussoukro' },
  { 'country': 'Jamaica', 'capital': 'Kingston' },
  { 'country': 'Japan', 'capital': 'Tokyo' },
  { 'country': 'Jordan', 'capital': 'Amman' },
  { 'country': 'Kazakhstan', 'capital': 'Astana' },
  { 'country': 'Kenya', 'capital': 'Nairobi' },
  { 'country': 'Kiribati', 'capital': 'Bairiki' },
  { 'country': 'Kuwait', 'capital': 'Kuwait' },
  { 'country': 'Kyrgyzstan', 'capital': 'Bishkek' },
  { 'country': 'Laos', 'capital': 'Vientiane' },
  { 'country': 'Latvia', 'capital': 'Riga' },
  { 'country': 'Lebanon', 'capital': 'Beirut' },
  { 'country': 'Lesotho', 'capital': 'Maseru' },
  { 'country': 'Liberia', 'capital': 'Monrovia' },
  { 'country': 'Libyan Arab Jamahiriya', 'capital': 'Tripoli' },
  { 'country': 'Liechtenstein', 'capital': 'Vaduz' },
  { 'country': 'Lithuania', 'capital': 'Vilnius' },
  { 'country': 'Luxembourg', 'capital': 'Luxembourg [Luxemburg/L' },
  { 'country': 'Macao', 'capital': 'Macao' },
  { 'country': 'North Macedonia', 'capital': 'Skopje' },
  { 'country': 'Madagascar', 'capital': 'Antananarivo' },
  { 'country': 'Malawi', 'capital': 'Lilongwe' },
  { 'country': 'Malaysia', 'capital': 'Kuala Lumpur' },
  { 'country': 'Maldives', 'capital': 'Male' },
  { 'country': 'Mali', 'capital': 'Bamako' },
  { 'country': 'Malta', 'capital': 'Valletta' },
  { 'country': 'Marshall Islands', 'capital': 'Dalap-Uliga-Darrit' },
  { 'country': 'Martinique', 'capital': 'Fort-de-France' },
  { 'country': 'Mauritania', 'capital': 'Nouakchott' },
  { 'country': 'Mauritius', 'capital': 'Port-Louis' },
  { 'country': 'Mayotte', 'capital': 'Mamoutzou' },
  { 'country': 'Mexico', 'capital': 'Ciudad de M' },
  { 'country': 'Micronesia, Federated States of', 'capital': 'Palikir' },
  { 'country': 'Moldova', 'capital': 'Chisinau' },
  { 'country': 'Monaco', 'capital': 'Monaco-Ville' },
  { 'country': 'Mongolia', 'capital': 'Ulan Bator' },
  { 'country': 'Montserrat', 'capital': 'Plymouth' },
  { 'country': 'Morocco', 'capital': 'Rabat' },
  { 'country': 'Mozambique', 'capital': 'Maputo' },
  { 'country': 'Myanmar', 'capital': 'Rangoon (Yangon)' },
  { 'country': 'Namibia', 'capital': 'Windhoek' },
  { 'country': 'Nauru', 'capital': 'Yaren' },
  { 'country': 'Nepal', 'capital': 'Kathmandu' },
  { 'country': 'Netherlands', 'capital': 'Amsterdam' },
  { 'country': 'Netherlands Antilles', 'capital': 'Willemstad' },
  { 'country': 'New Caledonia', 'capital': 'Noum' },
  { 'country': 'New Zealand', 'capital': 'Wellington' },
  { 'country': 'Nicaragua', 'capital': 'Managua' },
  { 'country': 'Niger', 'capital': 'Niamey' },
  { 'country': 'Nigeria', 'capital': 'Abuja' },
  { 'country': 'Niue', 'capital': 'Alofi' },
  { 'country': 'Norfolk Island', 'capital': 'Kingston' },
  { 'country': 'North Korea', 'capital': 'Pyongyang' },
  { 'country': 'Northern Ireland', 'capital': 'Belfast' },
  { 'country': 'Northern Mariana Islands', 'capital': 'Garapan' },
  { 'country': 'Norway', 'capital': 'Oslo' },
  { 'country': 'Oman', 'capital': 'Masqat' },
  { 'country': 'Pakistan', 'capital': 'Islamabad' },
  { 'country': 'Palau', 'capital': 'Koror' },
  { 'country': 'Palestine', 'capital': 'Gaza' },
  { 'country': 'Panama', 'capital': 'Ciudad de Panam' },
  { 'country': 'Papua New Guinea', 'capital': 'Port Moresby' },
  { 'country': 'Paraguay', 'capital': 'Asunci' },
  { 'country': 'Peru', 'capital': 'Lima' },
  { 'country': 'Philippines', 'capital': 'Manila' },
  { 'country': 'Pitcairn', 'capital': 'Adamstown' },
  { 'country': 'Poland', 'capital': 'Warszawa' },
  { 'country': 'Portugal', 'capital': 'Lisboa' },
  { 'country': 'Puerto Rico', 'capital': 'San Juan' },
  { 'country': 'Qatar', 'capital': 'Doha' },
  { 'country': 'Reunion', 'capital': 'Saint-Denis' },
  { 'country': 'Romania', 'capital': 'Bucuresti' },
  { 'country': 'Russian Federation', 'capital': 'Moscow' },
  { 'country': 'Rwanda', 'capital': 'Kigali' },
  { 'country': 'Saint Helena', 'capital': 'Jamestown' },
  { 'country': 'Saint Kitts and Nevis', 'capital': 'Basseterre' },
  { 'country': 'Saint Lucia', 'capital': 'Castries' },
  { 'country': 'Saint Pierre and Miquelon', 'capital': 'Saint-Pierre' },
  { 'country': 'Saint Vincent and the Grenadines', 'capital': 'Kingstown' },
  { 'country': 'Samoa', 'capital': 'Apia' },
  { 'country': 'San Marino', 'capital': 'San Marino' },
  { 'country': 'Sao Tome and Principe', 'capital': 'S' },
  { 'country': 'Saudi Arabia', 'capital': 'Riyadh' },
  { 'country': 'Scotland', 'capital': 'Edinburgh' },
  { 'country': 'Senegal', 'capital': 'Dakar' },
  { 'country': 'Seychelles', 'capital': 'Victoria' },
  { 'country': 'Sierra Leone', 'capital': 'Freetown' },
  { 'country': 'Singapore', 'capital': 'Singapore' },
  { 'country': 'Slovakia', 'capital': 'Bratislava' },
  { 'country': 'Slovenia', 'capital': 'Ljubljana' },
  { 'country': 'Solomon Islands', 'capital': 'Honiara' },
  { 'country': 'Somalia', 'capital': 'Mogadishu' },
  { 'country': 'South Africa', 'capital': 'Pretoria' },
  { 'country': 'South Georgia and the South Sandwich Islands', 'capital': null },
  { 'country': 'South Korea', 'capital': 'Seoul' },
  { 'country': 'South Sudan', 'capital': 'Juba' },
  { 'country': 'Spain', 'capital': 'Madrid' },
  { 'country': 'SriLanka', 'capital': null },
  { 'country': 'Sudan', 'capital': 'Khartum' },
  { 'country': 'Suriname', 'capital': 'Paramaribo' },
  { 'country': 'Svalbard and Jan Mayen', 'capital': 'Longyearbyen' },
  { 'country': 'Swaziland', 'capital': 'Mbabane' },
  { 'country': 'Sweden', 'capital': 'Stockholm' },
  { 'country': 'Switzerland', 'capital': 'Bern' },
  { 'country': 'Syria', 'capital': 'Damascus' },
  { 'country': 'Tajikistan', 'capital': 'Dushanbe' },
  { 'country': 'Tanzania', 'capital': 'Dodoma' },
  { 'country': 'Thailand', 'capital': 'Bangkok' },
  { 'country': 'The Democratic Republic of Congo', 'capital': null },
  { 'country': 'Togo', 'capital': 'Lom' },
  { 'country': 'Tokelau', 'capital': 'Fakaofo' },
  { 'country': 'Tonga', 'capital': 'Nuku\'alofa' },
  { 'country': 'Trinidad and Tobago', 'capital': 'Port-of-Spain' },
  { 'country': 'Tunisia', 'capital': 'Tunis' },
  { 'country': 'Turkey', 'capital': 'Ankara' },
  { 'country': 'Turkmenistan', 'capital': 'Ashgabat' },
  { 'country': 'Turks and Caicos Islands', 'capital': 'Cockburn Town' },
  { 'country': 'Tuvalu', 'capital': 'Funafuti' },
  { 'country': 'Uganda', 'capital': 'Kampala' },
  { 'country': 'Ukraine', 'capital': 'Kyiv' },
  { 'country': 'United Arab Emirates', 'capital': 'Abu Dhabi' },
  { 'country': 'United Kingdom', 'capital': 'London' },
  { 'country': 'United States', 'capital': 'Washington' },
  { 'country': 'United States Minor Outlying Islands', 'capital': null },
  { 'country': 'Uruguay', 'capital': 'Montevideo' },
  { 'country': 'Uzbekistan', 'capital': 'Toskent' },
  { 'country': 'Vanuatu', 'capital': 'Port-Vila' },
  { 'country': 'Venezuela', 'capital': 'Caracas' },
  { 'country': 'Vietnam', 'capital': 'Hanoi' },
  { 'country': 'Virgin Islands, British', 'capital': 'Road Town' },
  { 'country': 'Virgin Islands, U.S.', 'capital': 'Charlotte Amalie' },
  { 'country': 'Wales', 'capital': 'Cardiff' },
  { 'country': 'Wallis and Futuna', 'capital': 'Mata-Utu' },
  { 'country': 'Western Sahara', 'capital': 'El-Aai' },
  { 'country': 'Yemen', 'capital': 'Sanaa' },
  { 'country': 'Yugoslavia', 'capital': 'Beograd' },
  { 'country': 'Zambia', 'capital': 'Lusaka' },
  { 'country': 'Zimbabwe', 'capital': 'Harare' }
];
